on:
  workflow_call:
    inputs:
      versions:
        type: string
        required: true
        description: The publisher's version(s) string. It will be used as tag and tag-timestamp. >
          This is an array of strings, with only one string if it is latest. >
          TODO check for this in a step to make sure we don't overwrite the latest in the config.json.
      latest:
        type: boolean
        required: true
        description: If the version is considered the latest publisher version vs an earlier version.

jobs:
  build:
    name: Build the image.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON(inputs.versions) }}
      max-parallel: 1

    steps:
      - id: build
        run: echo building Docker image with version ${{ matrix.version }}

      - id: test
        run: echo testing

      - id: push
        run: echo pushing

